[package]
name = "gtuple_monomorphization"
version = "0.1.0"
edition = "2024"

# --------------------------------------------------
# crates.io 公開用の必須・推奨メタデータ
# --------------------------------------------------
description = "A proc-macro attribute to distribute trait methods over tuples of references."
license = "MIT"
authors = ["utasimaru <utasimaru@yahoo.co.jp>"] 
repository = "https://github.com/utasimaru/gtuple_monomorphization" 
readme = "README.md" 
keywords = ["proc-macro", "tuple", "trait", "macro"] 
categories = ["rust-patterns"] 

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
